### ISSUE TITLE
Setting inline styles in RTE editor makes text bold when it's not set to bold

### ISSUE THREAD

**Issue by stephenalion** [umbraco/Umbraco.Uno.Issues#41]
I edited manually the fontsizes and line-heights in the RTE editor. For some components it working, but on other components it seems to randomly make the text bold.

I expect it to work the same for every component. I hope this can get fixed soon, because the client wants to go live asap.

![Schermafbeelding 2020-10-06 om 17 21 40](https://user-images.githubusercontent.com/72454974/95301331-fa613a00-086f-11eb-9b2f-44ab69065671.png)
![Schermafbeelding 2020-10-07 om 09 30 20](https://user-images.githubusercontent.com/72454974/95301258-e1f11f80-086f-11eb-9ead-1704fbf64b14.png)
![Schermafbeelding 2020-10-07 om 09 30 27](https://user-images.githubusercontent.com/72454974/95301262-e3bae300-086f-11eb-87c3-1a8f315638a7.png)
![Schermafbeelding 2020-10-06 om 17 08 02](https://user-images.githubusercontent.com/72454974/95301297-eddce180-086f-11eb-927a-97d1e1848581.png)
![Schermafbeelding 2020-10-06 om 17 21 21](https://user-images.githubusercontent.com/72454974/95301329-f9300d00-086f-11eb-8ded-98de6f93c506.png)

**Comment by nul800sebastiaan** [comment]
Hi @stephenalion as far as I can tell the font is not set to bold, it has weight of 400 which is the default font weight for all browsers (`400` is also known as `normal`):

![image](https://user-images.githubusercontent.com/304656/95319692-8be4a200-0898-11eb-82c0-f73ccb7ffa8c.png)

I think this is expected behavior and you'll need to play with the font-weight here if you need it to look different.

**Comment by stephenalion** [comment]
hi @nul800sebastiaan thanks for your comment! I will try to change the font-weight.

**Comment by nul800sebastiaan** [comment]
No worries, I'll close this for now.
